### ISSUE TITLE
Wrong version of Node.js for Pi Zero

### ISSUE THREAD

**Issue by nickmomrik** [tinkertinker/biab-installer#17]
Seems like the installed version of Node.js is not compatible when using a Pi Zero, which needs to have an ARMv6 version. I think the Pi 1 also needs this arch type. I'm using a Pi Zero v1.3 but all of the Zero models use the ARMv6 chip.

Anytime you try to run `node` with the installed 6.9.4 version you get an "Illegal instruction" error.

After using `nvm` to uninstall and install (latest https://nodejs.org/dist/v7.7.2/node-v7.7.2-linux-armv6l.tar.xz), and then update the `/usr/bin/node` symlink, node works and I can successfully run `./biab`.

**Comment by nickmomrik** [comment]
Also note that with node not working when enabling the Camera module, a failed save error comes back. But... the option actually updates, so it looks like it worked. Then if you go to the Camera screen and Take a Photo you get a loading spinner that never seems to go away.

**Comment by johngodley** [comment]
Updated the image to 1.0.4 which uses armv6 - this should work on all Pi architectures.

Thanks Nick
