### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by johngodley** [tinkertinker/biab-installer#7]
- [ ] MacOS app icon
- [ ] Windows icon
- [ ] DMG icon
- [ ] DMG background

**Comment by jasmussen** [comment]
Put together this package with all of the above inside:

[icons.zip](https://github.com/tinkertinker/biab-installer/files/803236/icons.zip)

A lot of re-use from the desktop app here, but I think that's fine.

**Comment by johngodley** [comment]
I've added the DMG background in #12. We're already using the same icons for everything else. I'll mark this as done
